# PHB Redis Cache Infrastructure - CloudFormation Template
# Version: 1.0
# Last Updated: November 2, 2025

AWSTemplateFormatVersion: '2010-09-09'
Description: 'PHB Redis Cache Infrastructure for Drug Database Caching'

# ==================== PARAMETERS ====================

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - dev
      - staging
      - production
    Description: Environment name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where Redis will be deployed

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for Redis (minimum 2, different AZs)

  AppSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID of application servers that need Redis access

  CacheNodeType:
    Type: String
    Default: cache.t3.small
    AllowedValues:
      - cache.t3.micro     # $12/month - Dev/test
      - cache.t3.small     # $25/month - Small prod
      - cache.t3.medium    # $50/month - Medium prod
      - cache.t3.large     # $100/month - Large prod
      - cache.m6g.large    # $94/month - Enterprise (Graviton2)
      - cache.m6g.xlarge   # $188/month - Enterprise large
    Description: ElastiCache node type

  NumCacheClusters:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 6
    Description: Number of cache clusters (1 = no replication, 2+ = primary + replicas)

  SnapshotRetentionLimit:
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 35
    Description: Days to retain automated backups (0 = no backups)

  EnableEncryption:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable encryption at-rest and in-transit (recommended for production)

  AuthToken:
    Type: String
    Default: ''
    NoEcho: true
    Description: Redis AUTH token (optional, leave empty for no auth, min 16 chars if used)

# ==================== CONDITIONS ====================

Conditions:
  EnableReplication: !Not [!Equals [!Ref NumCacheClusters, 1]]
  EnableEncryptionCondition: !Equals [!Ref EnableEncryption, 'true']
  UseAuthToken: !And
    - !Condition EnableEncryptionCondition
    - !Not [!Equals [!Ref AuthToken, '']]

# ==================== RESOURCES ====================

Resources:

  # ==================== SUBNET GROUP ====================

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub 'PHB Redis Cache Subnet Group - ${Environment}'
      SubnetIds: !Ref SubnetIds
      CacheSubnetGroupName: !Sub 'phb-redis-subnet-${Environment}'
      Tags:
        - Key: Name
          Value: !Sub 'phb-redis-subnet-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: PHB

  # ==================== SECURITY GROUP ====================

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'phb-redis-${Environment}'
      GroupDescription: Security group for PHB Redis cache
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref AppSecurityGroupId
          Description: Allow Redis port from application servers
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub 'phb-redis-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: PHB

  # ==================== PARAMETER GROUP ====================

  RedisParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis7
      Description: !Sub 'PHB Redis parameter group - ${Environment}'
      Properties:
        maxmemory-policy: allkeys-lru  # Evict least recently used keys
        timeout: '300'  # Close idle connections after 5 minutes

  # ==================== REPLICATION GROUP ====================

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub 'phb-redis-${Environment}'
      ReplicationGroupDescription: !Sub 'PHB Drug Database Cache - ${Environment}'

      # Engine configuration
      Engine: redis
      EngineVersion: '7.1'
      Port: 6379
      CacheParameterGroupName: !Ref RedisParameterGroup

      # Cluster configuration
      CacheNodeType: !Ref CacheNodeType
      NumCacheClusters: !Ref NumCacheClusters

      # High availability
      AutomaticFailoverEnabled: !If [EnableReplication, true, false]
      MultiAZEnabled: !If [EnableReplication, true, false]

      # Network configuration
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds:
        - !Ref RedisSecurityGroup

      # Encryption
      AtRestEncryptionEnabled: !If [EnableEncryptionCondition, true, false]
      TransitEncryptionEnabled: !If [EnableEncryptionCondition, true, false]
      AuthToken: !If [UseAuthToken, !Ref AuthToken, !Ref 'AWS::NoValue']

      # Backup configuration
      SnapshotRetentionLimit: !Ref SnapshotRetentionLimit
      SnapshotWindow: '03:00-05:00'  # UTC

      # Maintenance window
      PreferredMaintenanceWindow: 'sun:05:00-sun:06:00'  # UTC

      # Auto upgrades (disabled for production)
      AutoMinorVersionUpgrade: false

      Tags:
        - Key: Name
          Value: !Sub 'phb-redis-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: PHB
        - Key: Purpose
          Value: Drug Database Cache

  # ==================== SNS TOPIC (Optional) ====================

  RedisSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'phb-redis-alerts-${Environment}'
      DisplayName: PHB Redis CloudWatch Alarms
      Tags:
        - Key: Name
          Value: !Sub 'phb-redis-alerts-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Subscribe email to SNS topic (optional - configure via console)
  # RedisSNSSubscription:
  #   Type: AWS::SNS::Subscription
  #   Properties:
  #     Protocol: email
  #     TopicArn: !Ref RedisSNSTopic
  #     Endpoint: devops@phb.ng

  # ==================== CLOUDWATCH ALARMS ====================

  CacheHitRateLowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'phb-redis-${Environment}-low-hit-rate'
      AlarmDescription: Cache hit rate below 85%
      MetricName: CacheHitRate
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: ReplicationGroupId
          Value: !Ref RedisReplicationGroup
      AlarmActions:
        - !Ref RedisSNSTopic

  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'phb-redis-${Environment}-high-cpu'
      AlarmDescription: Redis CPU utilization over 80%
      MetricName: CPUUtilization
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ReplicationGroupId
          Value: !Ref RedisReplicationGroup
      AlarmActions:
        - !Ref RedisSNSTopic

  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'phb-redis-${Environment}-high-memory'
      AlarmDescription: Redis memory usage over 85%
      MetricName: DatabaseMemoryUsagePercentage
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ReplicationGroupId
          Value: !Ref RedisReplicationGroup
      AlarmActions:
        - !Ref RedisSNSTopic

  EvictionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'phb-redis-${Environment}-evictions'
      AlarmDescription: Redis evicting keys (cache too small)
      MetricName: Evictions
      Namespace: AWS/ElastiCache
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ReplicationGroupId
          Value: !Ref RedisReplicationGroup
      AlarmActions:
        - !Ref RedisSNSTopic

# ==================== OUTPUTS ====================

Outputs:
  RedisPrimaryEndpoint:
    Description: Redis primary endpoint address
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-PrimaryEndpoint'

  RedisPort:
    Description: Redis port
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-Port'

  RedisURL:
    Description: Full Redis URL for REDIS_URL environment variable
    Value: !Sub
      - 'redis://${Endpoint}:${Port}/1'
      - Endpoint: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
        Port: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-RedisURL'

  RedisSecurityGroupId:
    Description: Security group ID for Redis
    Value: !Ref RedisSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  RedisReplicationGroupId:
    Description: ElastiCache replication group ID
    Value: !Ref RedisReplicationGroup
    Export:
      Name: !Sub '${AWS::StackName}-ReplicationGroupId'

  SNSTopicArn:
    Description: SNS topic ARN for Redis alerts
    Value: !Ref RedisSNSTopic
    Export:
      Name: !Sub '${AWS::StackName}-SNSTopicArn'

# ==================== USAGE INSTRUCTIONS ====================

# Deploy this stack:
# aws cloudformation create-stack \
#   --stack-name phb-redis-production \
#   --template-body file://cloudformation-redis-stack.yaml \
#   --parameters \
#     ParameterKey=Environment,ParameterValue=production \
#     ParameterKey=VpcId,ParameterValue=vpc-xxxxx \
#     ParameterKey=SubnetIds,ParameterValue="subnet-xxxxx,subnet-yyyyy" \
#     ParameterKey=AppSecurityGroupId,ParameterValue=sg-xxxxx \
#     ParameterKey=CacheNodeType,ParameterValue=cache.t3.small \
#     ParameterKey=NumCacheClusters,ParameterValue=2 \
#     ParameterKey=SnapshotRetentionLimit,ParameterValue=7 \
#     ParameterKey=EnableEncryption,ParameterValue=true \
#     ParameterKey=AuthToken,ParameterValue=YourSecureToken123! \
#   --capabilities CAPABILITY_IAM

# Update stack:
# aws cloudformation update-stack \
#   --stack-name phb-redis-production \
#   --template-body file://cloudformation-redis-stack.yaml \
#   --parameters ... (same as above)

# Delete stack:
# aws cloudformation delete-stack --stack-name phb-redis-production

# Get outputs:
# aws cloudformation describe-stacks \
#   --stack-name phb-redis-production \
#   --query 'Stacks[0].Outputs'
